 --- #YAML:1.0
 name: Business-DateTime
 abstract: Calculate business dates
 version: 0.0.1
 author:
   - Bob Stockdale <stocks@cpan.org>
 license: perl
 distribution_type: module
 requires:
   DateTime: 1
   Params::Validate: 0
 build_requires:
   Test::Class: 1
   Test::More: 0
   Test::Exception: 0
 urls:
   license: http://dev.perl.org/licenses/
