--- #YAML:1.0
name: Business-DateTime
abstract: Perl module for performing DateTime addition in business time
version: 0.0.4
author:
  - Bob Stockdale <stocks@cpan.org>
license: perl
distribution_type: module
requires:
  DateTime: 0
  Params::Validate: 0
build_requires:
  Test::Class: 0
  Test::More: 0
  Test::Exception: 0
urls:
  license: http://dev.perl.org/licenses/
